// <auto-generated />
using BeastRescue.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeastRescue.Migrations
{
    [DbContext(typeof(BeastRescueContext))]
    [Migration("20211029172152_Photos")]
    partial class Photos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BeastRescue.Beast", b =>
                {
                    b.Property<int>("BeastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Photo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Species")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Temperment")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("BeastId");

                    b.ToTable("Beasts");

                    b.HasData(
                        new
                        {
                            BeastId = 1,
                            Age = 15,
                            Description = "300+ pounds, black and pink blotch patterning, scarred snout",
                            Gender = "Male",
                            Name = "Doctor",
                            Photo = "https://unsplash.com/photos/_bweKYLQbGU",
                            Species = "Hog",
                            Temperment = "Aloof, but loving"
                        },
                        new
                        {
                            BeastId = 2,
                            Age = 2,
                            Description = "Goldeny, cream-colored fur. Slender.",
                            Gender = "Female",
                            Name = "Murna",
                            Photo = "https://unsplash.com/photos/BOuggN1tMEk",
                            Species = "Cow",
                            Temperment = "Very sweet; a goof"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
